### ISSUE TITLE
Describe Linux build procedure assuming Ubuntu 15.04

### ISSUE THREAD

**Issue by agibalov** [DAThriftPoC/common-thrift-hello-world#3]
As of today, the Linux build procedure is described for Debian 7. Because it's quite old already, a few very special steps required to get all the dependencies installed. Example:

> ``` bash
> $ wget http://http.us.debian.org/debian/pool/main/a/automake-1.14/automake_1.14.1-4_all.deb
> $ sudo dpkg -i automake_1.14.1-4_all.deb
> ```

Ubuntu 15.04 is more up to date and has most of the dependencies available via `apt-get`. Please describe the build process for Ubuntu 15.04.

**Comment by NPeganov** [comment]
I was curious is Ubuntu 15.04 exact OS that the customer considers as a target linux-based OS?

**Comment by agibalov** [comment]
Hi @NPeganov,

No, Ubuntu is not even close :-) Our goal one is to get things up and running, so apt-get all-the-stuff is definitely more reasonable approach than git clone && make.

**Comment by NPeganov** [comment]
Got it, thanks!

**Comment by AlexeyPsarev** [comment]
Done
