### ISSUE TITLE
Make Server app launch in HTTP mode, when specifying parameter --http

### ISSUE THREAD

**Issue by agibalov** [DAThriftPoC/common-thrift-hello-world#6]
As a user, I want our server to launch in HTTP mode when I specify the `--http` command line parameter. By default, it should listen on port 80, but if I want to change the port, I can do that by explicitly specifying the `--port` parameter.

Examples:

``` bash
# this should launch HTTP at port 80
./server --http

# this should launch HTTP at port 9090
./server --http --port 9090
```

**Comment by AlexeyPsarev** [comment]
Our server will be able to support HTTP and Buffered transport. What type of transport should it use by default?
